sudo: required
language: minimal
services:
- docker
script: "./ci/publish_docker.sh"
branches:
  except:
  - gh-pages
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: mqCt7uvlZ2pmT4CAr3nNSPRRo5BDRvLtwZHh720YosKm5uw20nzSnFbQ/SSLAxtFmY2DHUVUkseB98PZoZsOAPMlQU6fkUPNrCbgFKzXm3deGA3sva0NAtvD/tNGvCUVUeB5ZFKMh1WKQTmknBgFsTapB1+yNxGu5KOblggMvpq8eyT240a6ujSEK73EU/HudTQfRHEmEARnYk7jbJKErDjMmh9HfHLTts8FltKPWlxXuGMyLwV6ogfQlJG8oC+Ly0Fwy+QNaqIGn3t8HqUbY3U2ksw+r9EiQUvZ3ftNCW+bhJNXOEDothUGwESswdRKolXSS0Z1YWLo/7qF6qPfFPCWbQDTHrBpQ2vzjMn5zv8se/ZM5093ofk3TqRK1Pkb50ZrUnjE/MIxx9RFFqKUDXCTLMUjzrRylszhnvsVF21od6X1zVX+7B3DU/WPsRdQX0ewFQxIPbIesdOVYp7z38d1c++q/d+gYGKIRicGxa+c7TvwYK8DcdXtSIWTHekaj++y/ACxg6q6wugNvxQDdk77CKRcsPkhAjGnYhUcyIkgpbEPXguT96uyiRGmLr6eXoQHUpEHK2oI1lY/+UnF317rEmsePerSHpiqT356/GgzxeGDC5Z5wVDnTBXOW4PPH4PlfE7ERRatfrhpfEBEl+Qw5+Q9ISX7DP8IZW2xNc8=
  - secure: 0CIxzSs8dlDFf6fg/yWDMLHjB0d0dyUdSRwWpez3sGoVDgzhIjdDVZpL4uvQCKvM0OcqpFZDtydnQLJ/HDwcnH13R7bSsC+WEuL/XYQIEliMiUNol2wpbgeJ0G6uTirByUrKbwazqzv7L7iINsidG7+SiMCEWWnQFM6MtspEC4MeOCDwT5rKaEVQJkerHGVg5HiVAHS40rFL50X3p/xTXWPC7QDHOAUDkGP8RDcCantYlrSIwmNQdzH6j+M3GDB+qcPscDm7kXBvu8UZZk1MlQm3ZmC7Di+3BZBXAKOaVfUvGEzb3YdZod60L4zpvZmq57w2bKFy9YgC8Q2HEiP51jMbY7iQnVSciARInl46VJAZV3+7O+CAsMLftEvA2aBXM6i1M38fyxk+T8/jsKsPxzIAamd2ehV8Yk7GUXO1DwD9e0VLd9TMTHOxovaFQIDSO6A0atVrGilpLScN5gozRw/qQBYVJd5Ht7PmvvRy8slPDjeJofXoO+JsDPKK+4WbMOyKfgIvlYNfRo6+BrTCswBPU8y5oAU5QWNJBctwXiQiJ4Xo5w8HV+w199Ru1/rU3CwHPXJ5MXCKCQAK5zzkuJn7FPOaNe2NcHzVJdcebHDvRr7KnyAGC5ncPeQjsDG86EZ64EW5SSjUuRwGvCjbZaYl5GeV2xzIJXk5TIT+3tU=
