name: Docker Image CI

on: 
  push:
    branches:
      - 0.5.0
      - 0.6.0
      - 0.7.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Push to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davlum/livy
          tags: ${GITHUB_REF##*/}-spark2.4.4
